# services:
#   db:
#     image: postgres:latest
#     restart: always
#     environment:
#       POSTGRES_PASSWORD: example
#     ports:
#       - 5432:5432

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: ["./main", "-host=db", "-port=5432", "-user=postgres", "-password=example", "-dbname=postgres", "-sslmode=disable"]
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"